### ISSUE TITLE
CastHelloText-swift/HelloText-SwiftTests/Info.plist

### ISSUE THREAD

**Issue by bvcsu** [googlecast/CastHelloText-swift#3]
I'm not sure what I'm doing here but I'm getting a compile error.

ProcessInfoPlistFile /Users/beauvaughn/Library/Developer/Xcode/DerivedData/HelloText-Swift-coxfxoflxigenefnbpngwnhqxqyx/Build/Products/Debug-iphonesimulator/HelloText-SwiftTests.xctest/Info.plist HelloText-SwiftTests/Info.plist
    cd "/Users/beauvaughn/Software Projects/Xcode_Workspace/GitHub/CastHelloText-swift"
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-infoPlistUtility /Users/beauvaughn/Software\ Projects/Xcode_Workspace/GitHub/CastHelloText-swift/HelloText-SwiftTests/Info.plist -expandbuildsettings -format binary -platform iphonesimulator -o /Users/beauvaughn/Library/Developer/Xcode/DerivedData/HelloText-Swift-coxfxoflxigenefnbpngwnhqxqyx/Build/Products/Debug-iphonesimulator/HelloText-SwiftTests.xctest/Info.plist

error: could not read data from '/Users/beauvaughn/Software Projects/Xcode_Workspace/GitHub/CastHelloText-swift/HelloText-SwiftTests/Info.plist': The file “Info.plist” couldn’t be opened because there is no such file.

**Comment by grantkemp** [comment]
Looks like you are missing a file. How did you build your project?

**Comment by ianbarber** [comment]
Oh yeah, that's a bug in the project file. I'll clear that out and add update with the updates for 2.7/swift 1.2.

**Comment by grantkemp** [comment]
Thanks Ian,  could I make a feature request to implement the new remote view Api in IOS? I believe its coming out this week- and currently the docs aren't super useful.

**Comment by ianbarber** [comment]
https://github.com/googlecast/CastRemoteDisplay-iOS <- like that?

**Comment by grantkemp** [comment]
@ianbarber nearly but one for us swifties... eg https://github.com/googlecast/CastRemoteDisplay-iOS-Swift...--> Sadly 404 at the mo...

**Comment by ianbarber** [comment]
Yeah there is no Swift specific sample at the moment. Will make a note!

**Comment by ianbarber** [comment]
That plist should be removed now.
